micronaut:
  application:
    name: livrariaEngine
  server:
    cors:
      enabled: true
    port: 8082
  endpoints:
    health:
      enabled: true
  cassandra:
    default:
      clusterName: '"cassandra"'
      contactPoint: '"localhost"'
      port: 9042
      maxSchemaAgreementWaitSeconds: 20
      ssl: true
      consistencylevel: LOCAL_ONE
